# medical_diagnosis_tests.py
# Tests for the medical diagnosis expert system.
# Code generated by Gemini Flash 2.5 10/6/2025
# Refactored extensively by Brian Bird 10/11/2025

from inference_engine import get_diagnosis

print("--- Scenario 1: Influenza Chain ---")
patient_facts_1 = ['fever', 'cough', 'body_aches']
goal_recommendations_1 = get_diagnosis(patient_facts_1)
print("Diagnoses:", *(goal_recommendations_1.get('diagnoses') or ['None']))
print("Recommendations:", *(goal_recommendations_1.get('recommendations') or ['None']))
print()

print("--- Scenario 2: Common Cold ---")
patient_facts_2 = ['fever', 'cough', 'sore_throat']
goal_recommendations_2 = get_diagnosis(patient_facts_2)
print("Diagnoses:", *(goal_recommendations_2.get('diagnoses') or ['None']))
print("Recommendations:", *(goal_recommendations_2.get('recommendations') or ['None']))
print()

print("--- Scenario 3: Migraine ---")
patient_facts_3 = ['headache', 'nausea', 'light_sensitivity']
goal_recommendations_3 = get_diagnosis(patient_facts_3)
print("Diagnoses:", *(goal_recommendations_3.get('diagnoses') or ['None']))
print("Recommendations:", *(goal_recommendations_3.get('recommendations') or ['None']))
print()

print("--- Scenario 4: Food Poisoning ---")
patient_facts_4 = ['no_appetite', 'stomach_pain']
goal_recommendations_4 = get_diagnosis(patient_facts_4)
print("Diagnoses:", *(goal_recommendations_4.get('diagnoses') or ['None']))
print("Recommendations:", *(goal_recommendations_4.get('recommendations') or ['None']))
